### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by mujiezhang** [WenchenSONG/Prophage-Hunter#2]
Hi, Wenchen, prophage hunter is a nice tool for prophage detection and I have used it in web version a few years ago. However, I have several questions about it.
1.  Is the web of prophage hunter still work? I can not open it.
2. The linux version of prophage hunter is hard to install. I have done the installation step1,2,3,4 and run prophage hunter using the provided fasta file. However, I got lots of errors like below:
    '''''''
Use of uninitialized value $sample in concatenation (.) or string at ../../all_script/steps/NEW_seq_aa.pl line 24, <R_1> line 1418.
Use of uninitialized value $sample in concatenation (.) or string at ../../all_script/steps/NEW_seq_aa.pl line 24, <R_1> line 1419.
Use of uninitialized value $sample in concatenation (.) or string at ../../all_script/steps/NEW_seq_aa.pl line 24, <R_1> line 1420.
21/12/2023 21:47:45:545 Welcome to InterProScan-5.64-96.0
21/12/2023 21:47:45:546 Running InterProScan v5 in STANDALONE mode... on Linux
21/12/2023 21:47:50:017 RunID: node154.pi.sjtu.edu.cn_20231221_214749087_jldr
21/12/2023 21:47:57:911 Loading file /dssg/home/acct-clsjhh/clsjhh/zmj/software/prophage_hunter/Prophage-Hunter/Step1.Identifying_core_elements/HYP/seq_aa_1.fa
21/12/2023 21:47:57:914 Running the following analyses:
[Pfam-36.0]
Pre-calculated match lookup service DISABLED.  Please wait for match calculations to complete...
21/12/2023 21:47:58:692 30% completed
21/12/2023 21:49:01:069 70% completed
21/12/2023 21:49:02:917 80% completed
21/12/2023 21:49:14:037 100% done:  InterProScan analyses completed 

Warning: Could not connect to update server to verify current version. Please check at the Cufflinks website (http://cufflinks.cbcb.umd.edu).
No fasta index found for ../Input.fa. Rebuilding, please wait..
Fasta index rebuilt.
Can't open perl script "../../all_script/steps/Sequence_Extract_2.pl": No such file or directory
head: cannot open 'seq.Candidate_1.Tab' for reading: No such file or directory
tail: cannot open 'seq.Candidate_1.Tab' for reading: No such file or directory
Can't open perl script "../../all_script/steps/Tab_to_fa.pl": No such file or directory
Can't open perl script "../../all_script/steps/Tab_to_fa.pl": No such file or directory

Building a new DB, current time: 12/21/2023 21:49:17
New DB name:   /dssg/home/acct-clsjhh/clsjhh/zmj/software/prophage_hunter/Prophage-Hunter/Step3.Extending_to_termini_repeats/down.Candidate_1.fa
New DB title:  down.Candidate_1.fa
Sequence type: Nucleotide
Keep MBits: T
Maximum file size: 3000000000B
BLAST options error: File down.Candidate_1.fa does not exist
Command line argument error: Argument "query". File is not accessible:  `up.Candidate_1.fa'
Cannot open out.outfmt6.Candidate_1.txt: No such file or directory
--- Enter matrix name --------------------------------- up to 80 characters ---
--- Enter matrix author(s) ---------------------------- up to 80 characters ---
--- Enter matrix copyright notice --------------------- up to 80 characters ---
--- Enter matrix notes ----------------- (end with '.' on a line by itself) ---
done.

Cannot open ../Step3.Extending_to_termini_repeats/Candidates_with_termini_repeats.gtf: No such file or directory
Cannot open prophage.gff3: No such file or directory
ls: cannot access '../Step4.Calculating_PL_TO_AAC/PL.Candidate_*': No such file or directory
ls: cannot access '../Step4.Calculating_PL_TO_AAC/TO.Candidate_*': No such file or directory
ls: cannot access '../Step4.Calculating_PL_TO_AAC/AAC.Candidate_*': No such file or directory
Use of uninitialized value $max_num in numeric le (<=) at ../all_script/steps/Scoring.pl line 50.
cat: '../Step4.Calculating_PL_TO_AAC/Candidate_*.seq.Tab': No such file or directory
Warning: [blastp] Examining 5 or more matches is recommended
Warning: [blastp] Query is Empty!
21/12/2023 21:53:09:637 Welcome to InterProScan-5.64-96.0
21/12/2023 21:53:09:638 Running InterProScan v5 in STANDALONE mode... on Linux
21/12/2023 21:53:13:724 RunID: node154.pi.sjtu.edu.cn_20231221_215313261_27e5
21/12/2023 21:53:21:784 Loading file /dssg/home/acct-clsjhh/clsjhh/zmj/software/prophage_hunter/Prophage-Hunter/Step6.Annotation/Candidate_all.seq.fa

The FASTA input file /dssg/home/acct-clsjhh/clsjhh/zmj/software/prophage_hunter/Prophage-Hunter/Step6.Annotation/Candidate_all.seq.fa is empty.
Therefore there are no sequences for InterproScan to analyse
Finishing...
21:53:21.880 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Table "STEP_INSTANCE" not found; SQL statement:
select distinct stepinstan0_.id as id1_111_, stepinstan0_.bottom_model as bottom_m2_111_, stepinstan0_.bottom_protein as bottom_p3_111_, stepinstan0_.step_id as step_id4_111_, stepinstan0_.time_created as time_cre5_111_, stepinstan0_.top_model as top_mode6_111_, stepinstan0_.top_protein as top_prot7_111_ from public.step_instance stepinstan0_ where stepinstan0_.id not in  (select stepinstan1_.id from public.step_instance stepinstan1_ inner join public.step_execution executions2_ on stepinstan1_.id=executions2_.step_instance_id where executions2_.state=?) order by stepinstan0_.id desc [42102-199]
2023-12-21 21:53:21,883 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:363] ERROR - Exception thrown by StandaloneBlackBoxMaster: 
javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not prepare statement
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154) ~[hibernate-core-5.4.2.Final.jar:5.4.2.Final]
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181) ~[hibernate-core-5.4.2.Final.jar:5.4.2.Final]
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1538) ~[hibernate-core-5.4.2.Final.jar:5.4.2.Final]
	at org.hibernate.query.Query.getResultList(Query.java:165) ~[hibernate-core-5.4.2.Final.jar:5.4.2.Final]
	at uk.ac.ebi.interpro.scan.management.dao.StepInstanceDAOImpl.retrieveUnfinishedStepInstances(StepInstanceDAOImpl.java:101) ~[interproscan-management-5.64-96.0.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) ~[spring-aop-5.2.24.RELEASE.jar:5.2.24.RELEASE]
    ''''''
3. do you have a plan to provide a more integative version or a easier way to install it? 

Thanks!

**Comment by WenchenSONG** [comment]
1. Since the web server had always been attacked, we had canceled the web service.
2.  "Can't open perl script "../../all_script/steps/Sequence_Extract_2.pl": No such file or directory" Put folder "steps" under "all_script". Please check the folder "steps"  and the right path of these files from download "steps".

![image](https://github.com/WenchenSONG/Prophage-Hunter/assets/122762987/a402cac6-90eb-4694-b599-43d1a837fa97)

3. Please pay attention to BGI-research.

Thanks!

**Comment by mingxuLi-00** [comment]
I have encountered a similar issue. Where can I find the "steps" database? I could not locate it within the link you provided.

I would greatly appreciate any guidance you can provide to help resolve this issue. Thank you！

**Comment by mingxuLi-00** [comment]
I've encountered a similar problem, unable to find the files like '../../all_script/steps/Sequence_Extract_2.pl'. But I have already placed the 'steps' files in the correct location, they are indeed under this path.Warning: Could not connect to update server to verify current version. Please check at the Cufflinks website (http://cufflinks.cbcb.umd.edu).
Can't open perl script "../../all_script/steps/Sequence_Extract_2.pl": No such file or directory
head: cannot open 'seq.Candidate_1.Tab' for reading: No such file or directory
tail: cannot open 'seq.Candidate_1.Tab' for reading: No such file or directory
Can't open perl script "../../all_script/steps/Tab_to_fa.pl": No such file or directory
Can't open perl script "../../all_script/steps/Tab_to_fa.pl": No such file or directory


Building a new DB, current time: 07/15/2024 16:36:49
New DB name:   /home/limingxu/tools/Prophage-Hunter-main/Step3.Extending_to_termini_repeats/down.Candidate_1.fa
New DB title:  down.Candidate_1.fa
Sequence type: Nucleotide
Keep MBits: T
Maximum file size: 1000000000B
BLAST options error: File down.Candidate_1.fa does not exist
Command line argument error: Argument "query". File is not accessible:  `up.Candidate_1.fa'
Cannot open out.outfmt6.Candidate_1.txt: No such file or directory
GeneMark.hmm 400-day license.
License key "/home/limingxu/.gm_key" not found.
This file is neccessary in order to use GeneMark.hmm.
GeneMarkS: error on last system call, error code 256
Abort program!!!
Cannot open Input.fa.faa: No such file or directory
Cannot open host.seq.fa: No such file or directory
cut: host.seq.Tab: No such file or directory
Use of uninitialized value $tmp in scalar chop at ../all_script/steps/aa_to_stats.pl line 30, <R_1> line 1.
Use of uninitialized value $tmp in concatenation (.) or string at ../all_script/steps/aa_to_stats.pl line 31, <R_1> line 1.
grep: Input.fa.gff3: No such file or directory
Illegal division by zero at ../all_script/steps/Orientation.stats.pl line 21, <R_2> line 1.
Cannot open ../Step3.Extending_to_termini_repeats/Candidates_with_termini_repeats.gtf: No such file or directory
Cannot open prophage.gff3: No such file or directory
ls: cannot access '../Step4.Calculating_PL_TO_AAC/PL.Candidate_*': No such file or directory
ls: cannot access '../Step4.Calculating_PL_TO_AAC/TO.Candidate_*': No such file or directory
ls: cannot access '../Step4.Calculating_PL_TO_AAC/AAC.Candidate_*': No such file or directory
Use of uninitialized value $max_num in numeric le (<=) at ../all_script/steps/Scoring.pl line 50.
cat: '../Step4.Calculating_PL_TO_AAC/Candidate_*.seq.Tab': No such file or directory
Warning: [blastp] Query is Empty!
15/07/2024 16:36:50:439 Welcome to InterProScan-5.63-95.0
15/07/2024 16:36:50:440 Running InterProScan v5 in STANDALONE mode... on Linux
15/07/2024 16:36:54:581 RunID: localhost.localdomain_20240715_163654476_i8vp
15/07/2024 16:37:02:669 Loading file /home/limingxu/tools/Prophage-Hunter-main/Step6.Annotation/Candidate_all.seq.fa

The FASTA input file /home/limingxu/tools/Prophage-Hunter-main/Step6.Annotation/Candidate_all.seq.fa is empty.
Therefore there are no sequences for InterproScan to analyse
Finishing...
sort: cannot read: output.txt: No such file or directory
cut: output.sorted.txt: No such file or directory
cut: output.sorted.txt: No such file or directory
cut: output.sorted.txt: No such file or directory
ls: cannot access '../Step4.Calculating_PL_TO_AAC/Candidate_*.seq.Tab': No such file or directory
Cannot open ../Step3.Extending_to_termini_repeats/Candidates_with_termini_repeats.gtf: No such file or directory
ls: cannot access '../Step4.Calculating_PL_TO_AAC/PL.Candidate_*.txt': No such file or directory
Error in library(glmnet) : there is no package called ‘glmnet’
Execution halted
cp: cannot stat '../Step3.Extending_to_termini_repeats/Candidates_with_termini_repeats.gtf': No such file or directory
cat: '../Step4.Calculating_PL_TO_AAC/Candidate_*.gff': No such file or directory
ls: cannot access '../Step6.Annotation/Candidate_*.Annotation.txt': No such file or directory
Cannot open ../Step7.Identifying_closest_phage/Marker.best5.txt: No such file or directory

**Comment by mingxuLi-00** [comment]
I've encountered a similar problem, unable to find the files like '../../all_script/steps/Sequence_Extract_2.pl'. But I have already placed the 'steps' files in the correct location, they are indeed under this path.

**Comment by mingxuLi-00** [comment]
I've encountered a similar problem, unable to find the files like '../../all_script/steps/Sequence_Extract_2.pl'. But I have already placed the 'steps' files in the correct location, they are indeed under this path. 
![image](https://github.com/user-attachments/assets/b05fd97c-09f0-437c-b030-e1997166d9e3)
But I also encountered this kind of error.

Looking forward to your reply. Thank you for your help！

Warning: Could not connect to update server to verify current version. Please check at the Cufflinks website (http://cufflinks.cbcb.umd.edu).
Can't open perl script "../../all_script/steps/Sequence_Extract_2.pl": No such file or directory
head: cannot open 'seq.Candidate_1.Tab' for reading: No such file or directory
tail: cannot open 'seq.Candidate_1.Tab' for reading: No such file or directory
Can't open perl script "../../all_script/steps/Tab_to_fa.pl": No such file or directory
Can't open perl script "../../all_script/steps/Tab_to_fa.pl": No such file or directory


Building a new DB, current time: 07/15/2024 16:36:49
New DB name:   /home/limingxu/tools/Prophage-Hunter-main/Step3.Extending_to_termini_repeats/down.Candidate_1.fa
New DB title:  down.Candidate_1.fa
Sequence type: Nucleotide
Keep MBits: T
Maximum file size: 1000000000B
BLAST options error: File down.Candidate_1.fa does not exist
Command line argument error: Argument "query". File is not accessible:  `up.Candidate_1.fa'
Cannot open out.outfmt6.Candidate_1.txt: No such file or directory
GeneMark.hmm 400-day license.
License key "/home/limingxu/.gm_key" not found.
This file is neccessary in order to use GeneMark.hmm.
GeneMarkS: error on last system call, error code 256
Abort program!!!
Cannot open Input.fa.faa: No such file or directory
Cannot open host.seq.fa: No such file or directory
cut: host.seq.Tab: No such file or directory
Use of uninitialized value $tmp in scalar chop at ../all_script/steps/aa_to_stats.pl line 30, <R_1> line 1.
Use of uninitialized value $tmp in concatenation (.) or string at ../all_script/steps/aa_to_stats.pl line 31, <R_1> line 1.
grep: Input.fa.gff3: No such file or directory
Illegal division by zero at ../all_script/steps/Orientation.stats.pl line 21, <R_2> line 1.
Cannot open ../Step3.Extending_to_termini_repeats/Candidates_with_termini_repeats.gtf: No such file or directory
Cannot open prophage.gff3: No such file or directory
ls: cannot access '../Step4.Calculating_PL_TO_AAC/PL.Candidate_*': No such file or directory
ls: cannot access '../Step4.Calculating_PL_TO_AAC/TO.Candidate_*': No such file or directory
ls: cannot access '../Step4.Calculating_PL_TO_AAC/AAC.Candidate_*': No such file or directory
Use of uninitialized value $max_num in numeric le (<=) at ../all_script/steps/Scoring.pl line 50.
cat: '../Step4.Calculating_PL_TO_AAC/Candidate_*.seq.Tab': No such file or directory
Warning: [blastp] Query is Empty!
15/07/2024 16:36:50:439 Welcome to InterProScan-5.63-95.0
15/07/2024 16:36:50:440 Running InterProScan v5 in STANDALONE mode... on Linux
15/07/2024 16:36:54:581 RunID: localhost.localdomain_20240715_163654476_i8vp
15/07/2024 16:37:02:669 Loading file /home/limingxu/tools/Prophage-Hunter-main/Step6.Annotation/Candidate_all.seq.fa

The FASTA input file /home/limingxu/tools/Prophage-Hunter-main/Step6.Annotation/Candidate_all.seq.fa is empty.
Therefore there are no sequences for InterproScan to analyse
Finishing...
sort: cannot read: output.txt: No such file or directory
cut: output.sorted.txt: No such file or directory
cut: output.sorted.txt: No such file or directory
cut: output.sorted.txt: No such file or directory
ls: cannot access '../Step4.Calculating_PL_TO_AAC/Candidate_*.seq.Tab': No such file or directory
Cannot open ../Step3.Extending_to_termini_repeats/Candidates_with_termini_repeats.gtf: No such file or directory
ls: cannot access '../Step4.Calculating_PL_TO_AAC/PL.Candidate_*.txt': No such file or directory
Error in library(glmnet) : there is no package called ‘glmnet’
Execution halted
cp: cannot stat '../Step3.Extending_to_termini_repeats/Candidates_with_termini_repeats.gtf': No such file or directory
cat: '../Step4.Calculating_PL_TO_AAC/Candidate_*.gff': No such file or directory
ls: cannot access '../Step6.Annotation/Candidate_*.Annotation.txt': No such file or directory
Cannot open ../Step7.Identifying_closest_phage/Marker.best5.txt: No such file or directory

**Comment by WenchenSONG** [comment]
Something error in your file address.
Please remove all files, must remove all files and re-install.

Please Note:  Update **the absolute path** to "software.list", rather
                      Must put folder "steps" under "all_script",
                      Then run " sh generate.sh software.list" to generate prophage_hunter_RUN.sh.

Other note like GeneMark.hmm only had 400-day license, you should update your key.
"License key "/home/limingxu/.gm_key" not found."

Install ##### Install steps
1. download and install the above softwares and update the absolute path to software.list
2. download database "steps" from https://drive.google.com/drive/folders/18FuMPNeXBmpeAVOOb1Vc9aQYgMTD0iRZ?usp=share_link
3. **put folder "steps" under "all_script"**
4. run sh generate.sh software.list to generate prophage_hunter_RUN.sh

**Comment by mingxuLi-00** [comment]
> Something error in your file address. Please remove all files, must remove all files and re-install.
> 
> Please Note: Update **the absolute path** to "software.list", rather Must put folder "steps" under "all_script", Then run " sh generate.sh software.list" to generate prophage_hunter_RUN.sh.
> 
> Other note like GeneMark.hmm only had 400-day license, you should update your key. "License key "/home/limingxu/.gm_key" not found."
> 
> Install ##### Install steps
> 
> 1. download and install the above softwares and update the absolute path to software.list
> 2. download database "steps" from https://drive.google.com/drive/folders/18FuMPNeXBmpeAVOOb1Vc9aQYgMTD0iRZ?usp=share_link
> 3. **put folder "steps" under "all_script"**
> 4. run sh generate.sh software.list to generate prophage_hunter_RUN.sh

Thank you for your reply! I will try again according to your suggestions!
